<a href="https://colab.research.google.com/github/agarwalpratik/aiml/blob/main/Hyperparameter_Tuning_LinearRegression_50_Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#What is Hyperparameters?
#
# They are function parameters that we set in the Model Constructor
#

# Goal of Hyperparameter tuning is to IDENTIFY/DISCOVER the best parameter values to achieve the optimal score


# Try Cross Validation and Hyperparameter tuning for 50 Startups dataset (all possible algos). Create a report showcasing best param and best score for all possible algos

1. LinearRegression

2. KNeighborsRegressor

3. DecisionTreeRegressor

4. RandomForestRegressor

5. BaggingRegressor (in combination with LinearRegression, KNeighborsRegressor, DecisionTreeRegressor)

In [1]:
import pandas as pd
import numpy as np

In [17]:
data= pd.read_csv('50_Startups.csv')

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [19]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [20]:
features = data.iloc[:,:-1].values
label = data.iloc[:,-1].values

from sklearn.preprocessing import OneHotEncoder
oheForstate = OneHotEncoder(sparse_output=False)
oheForstate.fit(features[:,[3]])
dummyVariables = oheForstate.transform(features[:,[3]]).astype(int)


features = np.concatenate([dummyVariables,features[:,[0,1,2]]] , axis = 1)
features

array([[0, 0, 1, 165349.2, 136897.8, 471784.1],
       [1, 0, 0, 162597.7, 151377.59, 443898.53],
       [0, 1, 0, 153441.51, 101145.55, 407934.54],
       [0, 0, 1, 144372.41, 118671.85, 383199.62],
       [0, 1, 0, 142107.34, 91391.77, 366168.42],
       [0, 0, 1, 131876.9, 99814.71, 362861.36],
       [1, 0, 0, 134615.46, 147198.87, 127716.82],
       [0, 1, 0, 130298.13, 145530.06, 323876.68],
       [0, 0, 1, 120542.52, 148718.95, 311613.29],
       [1, 0, 0, 123334.88, 108679.17, 304981.62],
       [0, 1, 0, 101913.08, 110594.11, 229160.95],
       [1, 0, 0, 100671.96, 91790.61, 249744.55],
       [0, 1, 0, 93863.75, 127320.38, 249839.44],
       [1, 0, 0, 91992.39, 135495.07, 252664.93],
       [0, 1, 0, 119943.24, 156547.42, 256512.92],
       [0, 0, 1, 114523.61, 122616.84, 261776.23],
       [1, 0, 0, 78013.11, 121597.55, 264346.06],
       [0, 0, 1, 94657.16, 145077.58, 282574.31],
       [0, 1, 0, 91749.16, 114175.79, 294919.57],
       [0, 0, 1, 86419.7, 153514.11, 0.0],
 

In [49]:
# In sklearn cross validation is implemented in teh function named cross_val_score

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

model = KNeighborsRegressor()
model1 = LinearRegression()

scores = cross_val_score(model,
                         features,
                         label,
                         cv=3)

scores1 = cross_val_score(model1,
                         features,
                         label,
                         cv=4) #In theory, CV value can be any natural number. (5,10)

In [36]:
scores

array([ -3.9386974 , -11.10730902,  -3.19218231])

In [50]:
scores1

array([ 0.7343055 , -0.15150116, -0.95783317,  0.47030549])

In [51]:
scores1.mean()

0.023819165381747942

In [48]:
import warnings
warnings.filterwarnings("ignore")

CL = scores.mean()

#Step1: Initialize the algo
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
model = KNeighborsRegressor()
model1 = LinearRegression()

#Step2: Initialize K-Fold Cross Validation

from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, #This value MUST be equal to the cv value of cross_val_score
              shuffle=True,
              random_state=1) #For reproducing same o/p

#Step3: Initialize tracker to track the best sample
tracker = 0

for train,test in kfold.split(features):
  tracker += 1

  X_train,X_test,y_train,y_test = features[train],features[test],label[train],label[test]

  model.fit(X_train,y_train)

  print(f"KNeighborsRegressor")
  if model.score(X_test,y_test) >= CL:
    print(f"Test Score {model.score(X_test,y_test)} Train Score {model.score(X_train,y_train)} for Sample split {tracker}")

  model1.fit(X_train,y_train)
  print(f"LinearRegression")
  if model1.score(X_test,y_test) >= CL:
    print(f"Test Score {model1.score(X_test,y_test)} Train Score {model1.score(X_train,y_train)} for Sample split {tracker}")


KNeighborsRegressor
Test Score 0.7579061119663741 Train Score 0.8508533508338685 for Sample split 1
LinearRegression
Test Score 0.9649618042060308 Train Score 0.942446542689397 for Sample split 1
KNeighborsRegressor
Test Score 0.3252908351992806 Train Score 0.8808241726461998 for Sample split 2
LinearRegression
Test Score 0.8185106842705208 Train Score 0.9655319679423091 for Sample split 2
KNeighborsRegressor
Test Score 0.8730587961896251 Train Score 0.8486170269346693 for Sample split 3
LinearRegression
Test Score 0.8820715931491742 Train Score 0.957307628387595 for Sample split 3
KNeighborsRegressor
Test Score 0.785477568188829 Train Score 0.8359587284471295 for Sample split 4
LinearRegression
Test Score 0.9846245896509758 Train Score 0.939824209339928 for Sample split 4
KNeighborsRegressor
Test Score 0.7619422763251544 Train Score 0.8229069152317442 for Sample split 5
LinearRegression
Test Score 0.9156298183227459 Train Score 0.9499864582841221 for Sample split 5


In [38]:
#Goal: To identify the best Hyperparamter values for KNN that can give score >= 0.97
'''
KNeighborsClassifier(
  n_neighbors= Any positive integers,
  weights= ‘uniform’, ‘distance’
  algorithm= ‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’
  leaf_size= Any positive integers,
  p= 1,2,
  metric= 'minkowski'‘cityblock’‘cosine’'euclidean’‘haversine’‘l1’‘l2’‘manhattan’‘nan_euclidean’

'''

"\nKNeighborsClassifier(\n  n_neighbors= Any positive integers,\n  weights= ‘uniform’, ‘distance’\n  algorithm= ‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’\n  leaf_size= Any positive integers,\n  p= 1,2,\n  metric= 'minkowski'‘cityblock’‘cosine’'euclidean’‘haversine’‘l1’‘l2’‘manhattan’‘nan_euclidean’\n\n"

In [64]:
#Grid Search

#Step1: Create parameter list and parameter grid

weightParameter = ['uniform','distance']
n_neighborsParameter = np.arange(3,31)
algorithmParameter =['auto', 'ball_tree', 'kd_tree', 'brute']
metricParameter = ['minkowski','cityblock','cosine','euclidean','haversine','l1','l2','manhattan','nan_euclidean']
pParameter = np.arange(1,3)
positiveParameter = [True,False]
fit_interceptParameter = [True,False]
copy_XParameter = [True,False]
n_jobsParameter = np.arange(1,3)

#For ParamGrid
# key = parameterName
# value = valid Parameter arg

paramGrid = dict(n_neighbors=n_neighborsParameter,
                 weights=weightParameter,
                 algorithm=algorithmParameter,
                 metric=metricParameter,
                 p=pParameter)

paramGridForLR = dict(positive=positiveParameter,
                      fit_intercept=fit_interceptParameter,
                      copy_X=copy_XParameter,
                      n_jobs=n_jobsParameter)


#Step2: Initialize Algo

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
modelGridSearch = LinearRegression()

#Step3: Perform GridSearch

from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(modelGridSearch,
                    param_grid=paramGridForLR,
                    cv=4)

grid.fit(features,label)

GridSearchCV(cv=4, estimator=LinearRegression(),
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': array([1, 2]), 'positive': [True, False]})

In [65]:
grid.best_score_

0.042262453598191224

In [66]:
grid.best_estimator_

LinearRegression(fit_intercept=False, n_jobs=1, positive=True)

In [67]:
grid.best_params_

{'copy_X': True, 'fit_intercept': False, 'n_jobs': 1, 'positive': True}

In [68]:
#Randomized Search Method
# Some of the combinations are randomly selected

from sklearn.model_selection import RandomizedSearchCV

grid = RandomizedSearchCV(modelGridSearch,
                          param_distributions=paramGridForLR,
                          cv=4)

grid.fit(features,label)

RandomizedSearchCV(cv=4, estimator=LinearRegression(),
                   param_distributions={'copy_X': [True, False],
                                        'fit_intercept': [True, False],
                                        'n_jobs': array([1, 2]),
                                        'positive': [True, False]})

In [69]:
grid.best_score_

0.042262453598191224

In [70]:
grid.best_params_

{'positive': True, 'n_jobs': 2, 'fit_intercept': False, 'copy_X': False}