<a href="https://colab.research.google.com/github/agarwalpratik/aiml/blob/main/KNN_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a model that can predict whether the customer will make a purchase in my store
#based on customer's age and customer's estimated salary

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [4]:
data.Purchased.unique()

array([0, 1])

In [5]:
data.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [ ]:
#
# 0--- Bad customer
# 1--- Good customer

In [6]:
#Seperate data as features and label
features = data.iloc[:,0:2].values
label = data.iloc[:,2].values

In [7]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = KNeighborsClassifier(n_neighbors=7, p=1) #Default k=5
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.875 TrainScore: 0.86875 RS: 3
Test Score : 0.875 TrainScore: 0.846875 RS: 10
Test Score : 0.85 TrainScore: 0.8375 RS: 13
Test Score : 0.875 TrainScore: 0.859375 RS: 15
Test Score : 0.85 TrainScore: 0.84375 RS: 17
Test Score : 0.8625 TrainScore: 0.85 RS: 50
Test Score : 0.9 TrainScore: 0.840625 RS: 68
Test Score : 0.9 TrainScore: 0.840625 RS: 90
Test Score : 0.85 TrainScore: 0.840625 RS: 97
Test Score : 0.9125 TrainScore: 0.84375 RS: 116
Test Score : 0.9125 TrainScore: 0.865625 RS: 121
Test Score : 0.8625 TrainScore: 0.84375 RS: 124
Test Score : 0.875 TrainScore: 0.846875 RS: 125
Test Score : 0.8625 TrainScore: 0.846875 RS: 130
Test Score : 0.875 TrainScore: 0.853125 RS: 134
Test Score : 0.875 TrainScore: 0.853125 RS: 145
Test Score : 0.8625 TrainScore: 0.846875 RS: 184
Test Score : 0.85 TrainScore: 0.84375 RS: 190
Test Score : 0.875 TrainScore: 0.840625 RS: 192
Test Score : 0.9 TrainScore: 0.853125 RS: 199
Test Score : 0.9 TrainScore: 0.853125 RS: 203
Test Score : 0.875 

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")
X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=116)

In [9]:
#Step1: Initialize the algo
from sklearn.neighbors import KNeighborsClassifier
modelAlgo = KNeighborsClassifier(n_neighbors=7)

In [10]:
modelAlgo.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [11]:
print(f"Training score is {modelAlgo.score(X_train,y_train)} and Testing Score is {modelAlgo.score(X_test,y_test)}")

Training score is 0.84375 and Testing Score is 0.9125


In [12]:
modelAlgo.score(features,label)

0.8575

In [13]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(label,modelAlgo.predict(features))
confusionMatrix

array([[240,  17],
       [ 40, 103]])

In [14]:
from sklearn.metrics import classification_report
print(classification_report(label,modelAlgo.predict(features)))

              precision    recall  f1-score   support

           0       0.86      0.93      0.89       257
           1       0.86      0.72      0.78       143

    accuracy                           0.86       400
   macro avg       0.86      0.83      0.84       400
weighted avg       0.86      0.86      0.85       400



In [15]:
modelAlgo

KNeighborsClassifier(n_neighbors=7)

In [16]:
age = float(input("Enter your age : "))
salary = float(input("Enter your salary : "))

compatibleFeature = np.array([[age,salary]])

label = model.predict(compatibleFeature)

if label[0] == 0:
  print("Bad Customer")
else:
  print("Good Customer")

Enter your age : 20
Enter your salary : 5000000
Good Customer


#**Regression**

In [ ]:
#Goal: Create a model that can predict the salary of the employee based on his/her years of Experience

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('Salary_Data.csv')

In [ ]:
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 624.0 bytes


In [ ]:
#Note: If the label column has missing value, simply delete that record
data.dropna(inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 720.0 bytes


In [ ]:
data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [ ]:
#Seperate data as featues and label
features = data.iloc[:,[0]].values
label = data.iloc[:,[1]].values

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor


CL = 0.95
for rs in range(1,51):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=rs)
  model = KNeighborsRegressor()
  model.fit(X_train,y_train)

  testScore = model.score(X_test,y_test)
  trainScore = model.score(X_train,y_train)

  if testScore > trainScore and testScore >= CL:
    print(f"Test Score {testScore} and Train score {trainScore} and RandomState {rs}")


Test Score 0.9786307958676878 and Train score 0.9619808593156158 and RandomState 3
Test Score 0.9618582425037919 and Train score 0.9532563182453715 and RandomState 4
Test Score 0.96660935726366 and Train score 0.9637033873265679 and RandomState 11
Test Score 0.9698697715657303 and Train score 0.9633445165172075 and RandomState 12
Test Score 0.9668142735068967 and Train score 0.9622802988399365 and RandomState 17
Test Score 0.9570730746553712 and Train score 0.9568544234693718 and RandomState 21
Test Score 0.963817732959105 and Train score 0.9637882840567983 and RandomState 25
Test Score 0.9959823617551047 and Train score 0.9496914536811901 and RandomState 26
Test Score 0.970904263386092 and Train score 0.9639665473037619 and RandomState 27
Test Score 0.9632867003602682 and Train score 0.9611357649060983 and RandomState 29
Test Score 0.9580216329439444 and Train score 0.9506840150394438 and RandomState 30
Test Score 0.9697015471846242 and Train score 0.9653323436916821 and RandomState 3

In [ ]:
#Create train test split
# X_train --> training feature set
# y_train --> training label set
# X_test ---> testing feature set
# y_test ---> testing label set

# Usually we work with
#X_train,y_train ---- training set
#X_test,y_test ------ testing set

#Split Ratio ( 80-20 , 75-25, 65-35 )

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=10)

In [ ]:
#Build Model | Train Model | Data Convergence

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
#
# Check the quality of the model
#
# SL (Significance Level) = Standard Alpha Values (0.05, 0.01, 0.1) or Dynamic SL
#
# SL for our project = 0.05
# CL = 0.95 (I am expecting atleast 95% accuracy in my model prediction)
#

# When it comes to approving the model, always go for GENERALIZED MODEL
#
# GeneralizedModel : The MODEL THAT UNDERSTAND THE POPULATION'S NATURE / Pattern.
#
# Generalized model is something that satisfies the following criteria (Guideline from PN)
#
# a. Calc the evaluation score of trainingset and testing set
# b. Check below criteria
#       if testScore > trainScore and testScore >= CL:
#               Approve Model
#       else:
#               Reject the Model and Improve the same
#

In [ ]:
CL = 0.95

testScore = model.score(X_test,y_test)
trainScore = model.score(X_train,y_train)

print(f"Test Score {testScore} and Train score {trainScore}")

if testScore > trainScore and testScore >= CL:
  print("Approve Model")
else:
  print("Reject Model")

Test Score 0.9816423482070253 and Train score 0.9494673013344646
Approve Model


In [ ]:
#Equation contains y_intercept and coeff of each feature column
model.coef_

array([[9478.20557998]])

In [ ]:
model.intercept_

array([24704.0959376])

In [ ]:
# salary = 24704.0959376 + 9478.20557998 (yExperience)