<a href="https://colab.research.google.com/github/agarwalpratik/aiml/blob/main/LogisticRegressionExample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a model that can predict whether the customer will make a purchase in my store
#based on customer's age and customer's estimated salary

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("Social_Network_Ads.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
data.Purchased.unique()

array([0, 1])

In [ ]:
#
# 0--- Bad customer
# 1--- Good customer

In [24]:
#Seperate data as features and label
features = data.iloc[:,[0,1]].values
label = data.iloc[:,2].values

In [25]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.6875 TrainScore: 0.63125 RS: 3
Test Score : 0.7375 TrainScore: 0.61875 RS: 4
Test Score : 0.6625 TrainScore: 0.6375 RS: 5
Test Score : 0.65 TrainScore: 0.640625 RS: 6
Test Score : 0.675 TrainScore: 0.634375 RS: 7
Test Score : 0.675 TrainScore: 0.634375 RS: 8
Test Score : 0.65 TrainScore: 0.640625 RS: 10
Test Score : 0.6625 TrainScore: 0.6375 RS: 11
Test Score : 0.7125 TrainScore: 0.625 RS: 13
Test Score : 0.675 TrainScore: 0.634375 RS: 16
Test Score : 0.7 TrainScore: 0.628125 RS: 17
Test Score : 0.7 TrainScore: 0.628125 RS: 21
Test Score : 0.65 TrainScore: 0.640625 RS: 24
Test Score : 0.6625 TrainScore: 0.6375 RS: 25
Test Score : 0.75 TrainScore: 0.615625 RS: 26
Test Score : 0.675 TrainScore: 0.634375 RS: 27
Test Score : 0.7 TrainScore: 0.628125 RS: 28
Test Score : 0.6875 TrainScore: 0.63125 RS: 29
Test Score : 0.6875 TrainScore: 0.63125 RS: 31
Test Score : 0.6625 TrainScore: 0.6375 RS: 37
Test Score : 0.7 TrainScore: 0.628125 RS: 39
Test Score : 0.7 TrainScore: 0.628125

In [26]:
#Step1: Initialize the algo
from sklearn.linear_model import LogisticRegression
modelAlgo = LogisticRegression()

In [27]:
#Step2: Initialize RFE

from sklearn.feature_selection import RFE
selectFeatures = RFE(estimator=modelAlgo)

In [28]:
#Step3: Fit the data to the RFE object
selectFeatures.fit(features,label)

RFE(estimator=LogisticRegression())

In [29]:
#Step4: Identify the feature that has the highest ranking

selectFeatures.ranking_

array([2, 1])

In [12]:
#SFM Select from Model
# It is applicable for all algo

In [30]:
#Step1: Initialize the algo
from sklearn.linear_model import LogisticRegression
modelAlgo = LogisticRegression()

In [31]:
#Step2: Initialize SelectFromModel

from sklearn.feature_selection import SelectFromModel
selectFeatures = SelectFromModel(estimator=modelAlgo)

In [32]:
#Step3: Fit the data to the SFM object
selectFeatures.fit(features,label)

SelectFromModel(estimator=LogisticRegression())

In [33]:
#Step4: Identify the feature that has the highest support

selectFeatures.get_support()

array([False,  True])

In [34]:
#Seperate data as features and label
features = data.iloc[:,[1]].values
label = data.iloc[:,2].values

In [35]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.6875 TrainScore: 0.63125 RS: 3
Test Score : 0.7375 TrainScore: 0.61875 RS: 4
Test Score : 0.6625 TrainScore: 0.6375 RS: 5
Test Score : 0.65 TrainScore: 0.640625 RS: 6
Test Score : 0.675 TrainScore: 0.634375 RS: 7
Test Score : 0.675 TrainScore: 0.634375 RS: 8
Test Score : 0.65 TrainScore: 0.640625 RS: 10
Test Score : 0.6625 TrainScore: 0.6375 RS: 11
Test Score : 0.7125 TrainScore: 0.625 RS: 13
Test Score : 0.675 TrainScore: 0.634375 RS: 16
Test Score : 0.7 TrainScore: 0.628125 RS: 17
Test Score : 0.7 TrainScore: 0.628125 RS: 21
Test Score : 0.875 TrainScore: 0.746875 RS: 24
Test Score : 0.6625 TrainScore: 0.6375 RS: 25
Test Score : 0.75 TrainScore: 0.615625 RS: 26
Test Score : 0.675 TrainScore: 0.634375 RS: 27
Test Score : 0.7 TrainScore: 0.628125 RS: 28
Test Score : 0.6875 TrainScore: 0.63125 RS: 29
Test Score : 0.6875 TrainScore: 0.63125 RS: 31
Test Score : 0.6625 TrainScore: 0.6375 RS: 37
Test Score : 0.7 TrainScore: 0.628125 RS: 39
Test Score : 0.7 TrainScore: 0.62812