<a href="https://colab.research.google.com/github/agarwalpratik/aiml/blob/main/Winequality_red.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('winequality-red.csv')

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [9]:
data.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [3]:
features = data.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]].values
label = data.iloc[:,11].values

In [10]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.609375 TrainScore: 0.5723221266614542 RS: 1
Test Score : 0.584375 TrainScore: 0.5785770132916341 RS: 2
Test Score : 0.6 TrainScore: 0.5801407349491791 RS: 3
Test Score : 0.625 TrainScore: 0.5809225957779516 RS: 5
Test Score : 0.6 TrainScore: 0.584831899921814 RS: 6
Test Score : 0.603125 TrainScore: 0.581704456606724 RS: 16
Test Score : 0.63125 TrainScore: 0.5824863174354965 RS: 17
Test Score : 0.603125 TrainScore: 0.5785770132916341 RS: 22
Test Score : 0.60625 TrainScore: 0.5754495699765442 RS: 23
Test Score : 0.61875 TrainScore: 0.5746677091477717 RS: 25
Test Score : 0.6125 TrainScore: 0.5777951524628616 RS: 26
Test Score : 0.6125 TrainScore: 0.5785770132916341 RS: 27
Test Score : 0.6125 TrainScore: 0.5746677091477717 RS: 29
Test Score : 0.59375 TrainScore: 0.5809225957779516 RS: 30
Test Score : 0.625 TrainScore: 0.5824863174354965 RS: 31
Test Score : 0.615625 TrainScore: 0.581704456606724 RS: 37
Test Score : 0.628125 TrainScore: 0.5699765441751369 RS: 38
Test Score : 0

In [11]:
#Step1: Initialize the algo
from sklearn.linear_model import LogisticRegression
modelAlgo = LogisticRegression()

In [12]:
#Step2: Initialize RFE

from sklearn.feature_selection import RFE
selectFeatures = RFE(estimator=modelAlgo)

In [13]:
#Step3: Fit the data to the RFE object
selectFeatures.fit(features,label)

RFE(estimator=LogisticRegression())

In [14]:
#Step4: Identify the feature that has the highest ranking

selectFeatures.ranking_

array([4, 1, 3, 5, 2, 6, 7, 1, 1, 1, 1])

In [ ]:
#'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar','chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density','pH', 'sulphates', 'alcohol'

1,4,7,8,9,10

In [ ]:
#SFM Select from Model
# It is applicable for all algo

In [15]:
#Step1: Initialize the algo
from sklearn.linear_model import LogisticRegression
modelAlgo = LogisticRegression()

In [16]:
#Step2: Initialize SelectFromModel

from sklearn.feature_selection import SelectFromModel
selectFeatures = SelectFromModel(estimator=modelAlgo)

In [17]:
#Step3: Fit the data to the SFM object
selectFeatures.fit(features,label)

SelectFromModel(estimator=LogisticRegression())

In [18]:
#Step4: Identify the feature that has the highest support

selectFeatures.get_support()

array([False,  True, False, False, False, False, False, False,  True,
       False,  True])

In [ ]:
#1,8,10

In [19]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [20]:
features = data.iloc[:,[1,4,7,8,9,10]].values
label = data.iloc[:,11].values

In [21]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.60625 TrainScore: 0.5754495699765442 RS: 1
Test Score : 0.590625 TrainScore: 0.5645035183737295 RS: 3
Test Score : 0.625 TrainScore: 0.5691946833463644 RS: 5
Test Score : 0.578125 TrainScore: 0.5660672400312744 RS: 7
Test Score : 0.5875 TrainScore: 0.5746677091477717 RS: 9
Test Score : 0.578125 TrainScore: 0.5746677091477717 RS: 15
Test Score : 0.58125 TrainScore: 0.5793588741204065 RS: 16
Test Score : 0.603125 TrainScore: 0.5715402658326818 RS: 17
Test Score : 0.575 TrainScore: 0.565285379202502 RS: 20
Test Score : 0.578125 TrainScore: 0.5738858483189992 RS: 22
Test Score : 0.60625 TrainScore: 0.5707584050039093 RS: 23
Test Score : 0.60625 TrainScore: 0.5707584050039093 RS: 25
Test Score : 0.596875 TrainScore: 0.581704456606724 RS: 26
Test Score : 0.584375 TrainScore: 0.5762314308053167 RS: 27
Test Score : 0.575 TrainScore: 0.5691946833463644 RS: 29
Test Score : 0.603125 TrainScore: 0.5715402658326818 RS: 31
Test Score : 0.634375 TrainScore: 0.563721657544957 RS: 37
Tes

In [22]:
features = data.iloc[:,[1,8,10]].values
label = data.iloc[:,11].values

In [23]:
SL = 0.05
CL = 1-SL

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

for rs in range(1,300):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)
  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)
  bestTestScore = 0

  if testScore > trainScore:
    print(f"Test Score : {testScore} TrainScore: {trainScore} RS: {rs}")

Test Score : 0.6125 TrainScore: 0.5613760750586395 RS: 1
Test Score : 0.6125 TrainScore: 0.5684128225175918 RS: 3
Test Score : 0.63125 TrainScore: 0.5699765441751369 RS: 5
Test Score : 0.59375 TrainScore: 0.5715402658326818 RS: 6
Test Score : 0.596875 TrainScore: 0.5777951524628616 RS: 8
Test Score : 0.596875 TrainScore: 0.565285379202502 RS: 9
Test Score : 0.584375 TrainScore: 0.5738858483189992 RS: 13
Test Score : 0.59375 TrainScore: 0.5738858483189992 RS: 15
Test Score : 0.575 TrainScore: 0.5699765441751369 RS: 16
Test Score : 0.603125 TrainScore: 0.5699765441751369 RS: 17
Test Score : 0.575 TrainScore: 0.5668491008600469 RS: 18
Test Score : 0.6 TrainScore: 0.5707584050039093 RS: 20
Test Score : 0.6 TrainScore: 0.5629397967161845 RS: 23
Test Score : 0.609375 TrainScore: 0.565285379202502 RS: 25
Test Score : 0.584375 TrainScore: 0.5746677091477717 RS: 26
Test Score : 0.590625 TrainScore: 0.5754495699765442 RS: 27
Test Score : 0.575 TrainScore: 0.5731039874902267 RS: 29
Test Score : 0

In [ ]:
#normal Test Score : 0.64375 TrainScore: 0.5699765441751369 RS: 200
#RFE Test Score : 0.634375 TrainScore: 0.563721657544957 RS: 37
#SFM Test Score : 0.63125 TrainScore: 0.5645035183737295 RS: 181